name: EmaCrossTradingSignal

on:
  schedule:
  - cron: '13,28,43,58 * * * *'  # UTC 00:00 = 北京 08:00

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run main script
        env:
          WECHAT_WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK_URL }}   # 注入API令牌
        run: |
          wget https://mirrors.aliyun.com/pypi/packages/35/dc/e7fab66315fdd2e2eeb2e3dbb9d23ea615bafc1e9174a8965d310e40a3c2/ta_lib-0.6.3.tar.gz#sha256=0c628db09b3fab6e5c26979e608b674e7aecc10359c82ba8d53f729767a856ac
          tar -zxvf ta_lib-0.6.3.tar.gz
          cd TA-Lib-0.6.3
          pip install .
          cd ..
          pip3 install -r requirements.txt
          python3 main.py